spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${YOUR_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  ai:
    ollama:
      chat:
        model: llama3.1:latest
        options:
          temperature: 0.2
          model: llama3.1:latest
  application:
    name: spring-ollama-chat
  thymeleaf:
    cache: false
  threads:
    virtual:
      enabled: true